# Generated by Django 4.2.29 on 2026-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
