# Generated by Django 4.2.29 on 2026-03-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_customerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
