# Generated by Django 4.2.29 on 2026-03-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
