# Generated by Django 4.2.29 on 2026-03-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_contactrequest_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
