# Generated by Django 4.2.29 on 2026-03-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_product_material_product_price_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
