# Generated by Django 4.2.29 on 2026-03-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_contactrequest_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('paragraph_image', models.ImageField(blank=True, null=True, upload_to='about-page-images/')),
            ],
        ),
    ]
