# Generated by Django 4.2.29 on 2026-03-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
