# Generated by Django 4.2.29 on 2026-03-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_aboutpage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
