# Generated by Django 4.2.29 on 2026-03-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
