# Generated by Django 4.2.29 on 2026-04-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_faq_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='svg_icon',
            field=models.FileField(blank=True, null=True, upload_to='social-media-icons/'),
        ),
    ]
